// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

#pragma once

#include "rocprofvis_widget.h"

namespace RocProfVis
{
namespace View
{

class TabContainer : public RocWidget
{
public:
    TabContainer();
    virtual ~TabContainer();

    virtual void Render();
    virtual void Update();

    void AddTab(const TabItem& tab);
    void AddTab(TabItem&& tab);

    void RemoveTab(const std::string& id);
    void RemoveTab(int index);

    void SetActiveTab(int index);
    void SetActiveTab(const std::string& id);

    void SetTabLabel(const std::string& label, const std::string& id);

    const TabItem* GetActiveTab() const;

#ifdef IMGUI_ENABLE_TEST_ENGINE
    int GetActiveTabIndexForTest() const { return m_active_tab_index; }
    int GetTabCountForTest() const { return static_cast<int>(m_tabs.size()); }
    // ImGui item id of tab `index`'s header, captured at render. Drive the tab
    // via ctx->ItemClick(this id): the tab is wrapped in PushID so its path is
    // unstable, and a raw mouse click does not reliably activate it. 0 if not drawn.
    unsigned int GetTabHeaderIdForTest(int index) const
    {
        if(index < 0 || index >= static_cast<int>(m_tab_header_rects_for_test.size()))
            return 0;
        if(!m_tab_header_rects_for_test[index].valid) return 0;
        return m_tab_header_rects_for_test[index].id;
    }
#endif

    void SetAllowToolTips(bool allow_tool_tips);
    bool GetAllowToolTips() const;

    const std::vector<const TabItem*> GetTabs();

    void               SetEventSourceName(const std::string& source_name);
    const std::string& GetEventSourceName() const;

    void EnableSendCloseEvent(bool enable);
    void EnableSendChangeEvent(bool enable);

private:
    void                 ShowCloseTabConfirm(int tab_index);
    void                 SendEvent(RocEvents event, const std::string& tab_id);
    std::vector<TabItem> m_tabs;
    int                  m_active_tab_index;  // index of the currently active tab
    int  m_set_active_tab_index;      // used to programmatically set the active tab
    int  m_pending_to_remove;
    bool m_allow_tool_tips;           // whether to show tooltips for tabs
    bool m_enable_send_close_event;   // enable sending close tab events
    bool m_enable_send_change_event;  // enable sending tab selection events

    // Friendly source name for events generated by this container. If empty, the
    // source name will be the m_widget_name
    std::string m_event_source_name;

    std::unique_ptr<ConfirmationDialog> m_confirmation_dialog;
    static constexpr int                s_invalid_index = -1;

#ifdef IMGUI_ENABLE_TEST_ENGINE
    struct TabHeaderRectForTest
    {
        bool         valid = false;
        unsigned int id    = 0;
    };
    std::vector<TabHeaderRectForTest> m_tab_header_rects_for_test;
#endif
};

}  // namespace View
}  // namespace RocProfVis
